package:
  name: example-py-package
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: ..
  git_rev: {{ GIT_FULL_HASH }}

build:
  noarch: python
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: py{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
    - wheel
    - setuptools_scm
  run:
    - python =3.9
    - requests >2

test:
  imports:
    - example_py_package
  requires:
    - pytest
    - pytest-cov
  source_files:
    - tests
  commands:
    - pytest

